site_name: Elevate Documentation

repo_name: thomaschampagne/elevate
repo_url: https://github.com/thomaschampagne/elevate

dev_addr: localhost:8000

theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: deep purple
  features:
    - navigation.sections
    - navigation.top

markdown_extensions:
- toc:
    permalink: true

nav:
  - Download & Install:
      - Windows: Download-&-Install/Windows.md
      - macOS: Download-&-Install/macOS.md
  - Frequently Asked Questions:
      - All Platforms: Frequently-Asked-Questions/All-Platforms.md
      - Desktop App: Frequently-Asked-Questions/Desktop-App.md
      - Web Extension: Frequently-Asked-Questions/Web-Extension.md
  - Roadmap:
      - Desktop App: Roadmap/Desktop-App.md
      - Web Extension: Roadmap/Web-Extension.md
  - Privacy: Privacy.md
