site_name: Elevate Documentation

repo_name: thomaschampagne/elevate
repo_url: https://github.com/thomaschampagne/elevate

dev_addr: localhost:8000

theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: deep purple
  features:
    - navigation.sections
    - navigation.top

markdown_extensions:
- toc:
    permalink: true
